module.exports = () => {
  global.router.post('/desktop/social/addNewPost', require('../../../controllers/desktop/social/addNewPost'))
  global.router.post('/desktop/social/deleteCommentsById', require('../../../controllers/desktop/social/deleteCommentsById'))
  global.router.post('/desktop/social/editPost', require('../../../controllers/desktop/social/editPost'))
  global.router.post('/desktop/social/getPostComments', require('../../../controllers/desktop/social/getPostComments'))
  global.router.post('/desktop/social/getPostDetailById', require('../../../controllers/desktop/social/getPostDetailById'))
  global.router.post('/desktop/social/getPostsList', require('../../../controllers/desktop/social/getPostsList'))
  global.router.post('/desktop/social/inactivatePost', require('../../../controllers/desktop/social/inactivatePost'))
  global.router.post('/desktop/social/createNewSchoolEvent', require('../../../controllers/desktop/social/createNewSchoolEvent'))
  global.router.post('/desktop/social/getSchoolEvents', require('../../../controllers/desktop/social/getSchoolEvents'))
  global.router.post('/desktop/social/getSchoolEventDetail', require('../../../controllers/desktop/social/getSchoolEventDetail'))
  global.router.post('/desktop/social/updateSchoolEvent', require('../../../controllers/desktop/social/updateSchoolEvent'))
  global.router.post('/desktop/social/changeStatusSchoolEvent', require('../../../controllers/desktop/social/changeStatusSchoolEvent'))
  global.router.post('/desktop/social/createNote', require('../../../controllers/desktop/social/createNote'))
  global.router.post('/desktop/social/getNotes', require('../../../controllers/desktop/social/getNotes'))
  global.router.post('/desktop/social/getNoteDetailById', require('../../../controllers/desktop/social/getNoteDetailById'))
  global.router.post('/desktop/social/changeNoteStatus', require('../../../controllers/desktop/social/changeNoteStatus'))
  global.router.post('/desktop/social/updateNote', require('../../../controllers/desktop/social/updateNote'))
  global.router.post('/desktop/social/getChildrenByEventId', require('../../../controllers/desktop/social/getChildrenByEventId'))
  global.router.post('/desktop/social/getGenericPostDetail', require('../../../controllers/desktop/social/getGenericPostDetail'))
  global.router.post('/desktop/social/deletePost', require('../../../controllers/desktop/social/deletePost'))
}